/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { THANKToken__factory } from "./THANKToken__factory";
export { ThankReward__factory } from "./ThankReward__factory";
